version: "3.8"

services:
  my-ai-agent:
    build: .
    container_name: my-ai-agent
    ports:
      - "8000:8000"
    # Add environment variables or volume mounts if needed
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000

  # Additional service
  dapr_placement:
    image: daprio/dapr
    command: ["./placement", "-port", "50005"]
    container_name: dapr_placement
    ports:
      - "50005:50005"
