[tool.poetry]
name = "aiagent-microservice"
version = "0.1.0"
description = "A mock AI agent using FastAPI + LangGraph + Dapr."
authors = ["Jerome Mohanan <2962518+jero2rome@users.noreply.github.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.95.0"
uvicorn = "^0.21.1"
langgraph = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
